#!/usr/bin/env python3
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
INSTALL_PREFIX = os.path.normpath(os.path.join(SCRIPT_DIR, '..', '..'))
EXECUTABLE = os.path.join(INSTALL_PREFIX, 'bin', 'bird_detector_node')
if not os.path.isfile(EXECUTABLE):
    EXECUTABLE = os.path.join(os.path.dirname(INSTALL_PREFIX), 'bin', 'bird_detector_node')

if __name__ == '__main__':
    os.execv(EXECUTABLE, [EXECUTABLE] + sys.argv[1:])
